@extends('layouts.demo')
@section('title', 'Under the canvas · Platno')
@section('content')
<article class="developer-page">
<p class="eyebrow">FOR THE PEOPLE WHO BUILD</p><h1>Laravel at heart.<br>Yours to <em>extend.</em></h1><p class="lead">A ready-made visual editor, portable structured content, and a small PHP-and-Blade contract for your own blocks.</p>
<section class="developer-section"><h2>What you install.</h2><div><p><strong>Platno is the Laravel package.</strong> It provides the editor, page management, private drafts, publication history, media and Blade rendering. The normal path needs no Node build, frontend framework or paid service.</p><p><strong>This website is a separate demo application.</strong> It adds the visual presentation, sample content, private 24-hour spaces and cleanup. Those lifetime rules are not part of the package.</p><a href="https://github.com/gogoSpace/laravel-platno#quick-start">Install the Experimental Preview ↗</a></div></section>
<section class="developer-section"><h2>One editor.<br>Your framework.</h2><div><p>Vue, React and Livewire mount the same native JavaScript editor directly in your application, using Shadow DOM. Your application owns its routes and access rules. Platno does not supply authentication.</p><p>Start a demo, then use the integration selector in the studio. Every integration edits the same page in your own space.</p><div class="framework-links"><a href="/studio?adapter=native">Native ↗</a><a href="/studio?adapter=vue">Vue ↗</a><a href="/studio?adapter=react">React ↗</a><a href="/studio?adapter=livewire">Livewire ↗</a></div><pre><code>&lt;PlatnoEditor
    editor-address="/platno/pages/42/edit"
    @change="handleUnsavedChanges"
    @state="handleSavedRevision"
/&gt;</code></pre><p>The adapters are examples to copy into your application. They currently edit Platno pages; binding an arbitrary model field is not implemented.</p><a href="https://github.com/gogoSpace/laravel-platno/tree/main/examples/adapters">Integration code and lifecycle contract ↗</a></div></section>
<section class="developer-section" id="plugins"><h2>Your first block.</h2><div><p>The templates use standard Platno blocks plus two demo-owned examples: Hero and Quote. Their PHP definitions and Blade templates are part of this demo's source.</p><pre><code>php artisan platno:make-plugin Callout --type=example.callout</code></pre><p>Define the fields, validate the data and render it in Blade. The editor generates the inspector from those fields. The canvas and published page use the same renderer.</p><a href="https://github.com/gogoSpace/laravel-platno/blob/main/docs/plugins.md">Build a custom block ↗</a><br><a href="https://github.com/gogoSpace/platno-demo/tree/main/app/Plugins">Inspect the demo plugins ↗</a></div></section>
<section class="developer-section"><h2>From draft<br>to published.</h2><div><p>Saving changes your private draft. Publishing creates a snapshot of that saved revision. Later edits stay private until you publish them again. Revision checks prevent a stale browser from silently overwriting newer content.</p><p>In this demo, published links and uploaded media expire with the workspace. The package itself imposes no such expiration.</p></div></section>
<section class="developer-section"><h2>Experimental<br>by design.</h2><div><p>This is a pre-alpha working prototype. APIs and content formats may change, and it is not ready for production use.</p><p>Current boundaries include no collaborative editing, raw HTML, automatic plugin-data migrations, image cropping or derivatives. SQLite and local storage have been verified; other database engines and remote disks have not.</p><a href="https://github.com/gogoSpace/laravel-platno/blob/main/docs/compatibility.md">Compatibility and verification ↗</a><br><a href="https://github.com/gogoSpace/laravel-platno/issues">Share feedback or report a bug ↗</a></div></section>
</article>
@endsection
